package ua.bizbiz.testspringstatemachine.entity;

public enum Events {
  
  ENTER_ADMIN_SECRET_CODE, ENTER_USER_SECRET_CODE, ENTER_INCORRECT_SECRET_CODE,
  GET_USERS, FAIL_GET_USERS,
  CREATE_USER, UPDATE_USER, READ_USER, DELETE_USER,
  ENTER_CORRECT_USER_INFO, ENTER_INCORRECT_USER_INFO,
}
